version: '3.8'

services:
  mi-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-servidor-compose
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html